name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello, how are you doing?"
          echo "Are you ready to explore more?"
      - name: Print bye
        run: echo "Bye, have a good day!"
