name: Lint, Test and Deploy
on: workflow_dispatch #[push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: action-reaction-project

        steps: 
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            
            - name: install dependencies
              run: npm ci
              
            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm test

            - name: Build Project
              run: npm run build
            
            - name: Deploy Success
              run: echo "Deployment Successful"