name: Activity Type Trigger on pull request
on:
  pull_request:
    types: 
      - opened
  workflow_dispatch:
jobs:
    activity_type_trigger:
        runs-on: ubuntu-latest
    
        steps:
            - name: output event name
              run: echo "${{ toJSON(github.event_name) }}"

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            
            - name: install dependencies
              run: npm ci
              working-directory: action-reaction-project

            - name: Run tests
              run: npm test
              working-directory: action-reaction-project

            - name: Build Project
              run: npm run build
              working-directory: action-reaction-project
            
            - name: Deploy Success
              run: echo "Deployment Successful"