name: Dependency Caching
on: 
    push:
        branches:
        - main
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Cache NodeJS dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: install dependencies
              run: npm ci
              working-directory: action-reaction-project

            - name: Lint code
              run: npm run lint
              working-directory: action-reaction-project

            - name: run test cases
              run: npm test
              working-directory: action-reaction-project
    
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Cache NodeJS dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install dependencies
              run: npm ci
              working-directory: action-reaction-project
            
            - name: Build the project
              run: npm run build
              working-directory: action-reaction-project

            - name: Deploy the package
              run: echo "Deployed the package..."