name: matrix
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [16, 18, 20]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
        
            - name: Install dependencies
              run: npm ci
              working-directory: action-reaction-project

            - name: Run Build
              run: npm run build
              working-directory: action-reaction-project