name: issue notify
on: issues
jobs:
    issue_notify:
        runs-on: ubuntu-latest
        steps:
            - name: output issue details
              run: |
                echo "Issue Title: ${{ github.event.issue.title }}"
                echo "Issue Body: ${{ github.event.issue.body }}"
                echo "Issue URL: ${{ github.event.issue.html_url }}"
                echo "-----------------"
                echo "All details: ${{ github.event }}"